### ISSUE TITLE
Dependencies issue?

### ISSUE THREAD

**Issue by gladkikhartem** [manahl/okcli#9]
$ sudo pip install okcli
$ okcli
Traceback (most recent call last):
  File "/usr/local/bin/okcli", line 5, in <module>
    from okcli.main import cli
  File "/usr/local/lib/python3.10/dist-packages/okcli/main.py", line 20, in <module>
    from cli_helpers.tabular_output import TabularOutputFormatter
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/tabular_output/__init__.py", line 11, in <module>
    from .output_formatter import format_output, TabularOutputFormatter
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/tabular_output/output_formatter.py", line 10, in <module>
    from . import (delimited_output_adapter, vertical_table_adapter,
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 4, in <module>
    from cli_helpers.packages import tabulate
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/packages/tabulate.py", line 6, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by gladkikhartem** [comment]
$ sudo pip install okcli
$ okcli
Traceback (most recent call last):
  File "/usr/local/bin/okcli", line 5, in <module>
    from okcli.main import cli
  File "/usr/local/lib/python3.10/dist-packages/okcli/main.py", line 20, in <module>
    from cli_helpers.tabular_output import TabularOutputFormatter
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/tabular_output/__init__.py", line 11, in <module>
    from .output_formatter import format_output, TabularOutputFormatter
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/tabular_output/output_formatter.py", line 10, in <module>
    from . import (delimited_output_adapter, vertical_table_adapter,
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 4, in <module>
    from cli_helpers.packages import tabulate
  File "/usr/local/lib/python3.10/dist-packages/cli_helpers/packages/tabulate.py", line 6, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by gladkikhartem** [comment]
OS: Linux Mint 
Default Python version:  Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux

**Comment by telefunken** [comment]
The ImportError you're encountering is due to a change in Python 3.10 where Iterable has been moved from collections to collections.abc.
Try Python 3.9 or earlier if the problem is in a dependency that can't be updated.
